// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1cXRS5ryj0Zi_CmgxFzpt9a3AtzSscNg',
    appId: '1:831072167532:web:b9693c02e9f85e3ad21a49',
    messagingSenderId: '831072167532',
    projectId: 'getfit4me',
    authDomain: 'getfit4me.firebaseapp.com',
    storageBucket: 'getfit4me.firebasestorage.app',
    measurementId: 'G-622WQ01X4M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwTnL0rFqsg3gHoK8A0Jd_uW1Giy_eahc',
    appId: '1:831072167532:android:8d44443cf3409949d21a49',
    messagingSenderId: '831072167532',
    projectId: 'getfit4me',
    storageBucket: 'getfit4me.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0I1Hri7K_LUAkAeADRj603Fc5ZcbgPNg',
    appId: '1:831072167532:ios:7b7c8315b57c5742d21a49',
    messagingSenderId: '831072167532',
    projectId: 'getfit4me',
    storageBucket: 'getfit4me.firebasestorage.app',
    iosBundleId: 'com.example.getfit4me',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0I1Hri7K_LUAkAeADRj603Fc5ZcbgPNg',
    appId: '1:831072167532:ios:7b7c8315b57c5742d21a49',
    messagingSenderId: '831072167532',
    projectId: 'getfit4me',
    storageBucket: 'getfit4me.firebasestorage.app',
    iosBundleId: 'com.example.getfit4me',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1cXRS5ryj0Zi_CmgxFzpt9a3AtzSscNg',
    appId: '1:831072167532:web:57a670a39ca06fc2d21a49',
    messagingSenderId: '831072167532',
    projectId: 'getfit4me',
    authDomain: 'getfit4me.firebaseapp.com',
    storageBucket: 'getfit4me.firebasestorage.app',
    measurementId: 'G-JV4KKEN005',
  );
}
